# Change these first
owner: CyberLions-Italian-Community # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

user-agent: CyberLions-Italian-Community

sites:
  - name: Sito web
    url: https://cyberlions-ita.eu
    assignees:
      - Trainax
      - TheGITofTeo997
  - name: Pagina social
    url: https://social.cyberlions-ita.eu
    assignees:
      - Trainax
      - TheGITofTeo997
  - name: Server TeamSpeak
    check: "tcp-ping"
    url: 164.132.251.188
    port: 30033
    assignees:
      - TheGITofTeo997
  - name: SinusBot
    check: "tcp-ping"
    url: 217.182.128.229
    port: 8087
    assignees:
      - TheGITofTeo997
  - name: Infrastruttura principale
    check: "tcp-ping"
    url: 217.182.128.229
    port: 22
    assignees:
      - TheGITofTeo997

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cyberlions-ita.eu
  # baseUrl: /status
  logoUrl: https://cyberlions-ita.eu/images/brown.png
  name: CyberLions Italian Community Status Page
  introTitle: "CyberLions Italian Community Status Page"
  introMessage: "Qui puoi vedere lo stato dei nostri servizi"
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CyberLions-Italian-Community/status

i18n:
  activeIncidentSummary: "Aperto il $DATE con $POSTS post"
  activeIncidents: "Incidenti attivi"
  allSystemsOperational: "Tutti i sistemi operativi"
  averageResponseTime: "Tempo medio di risposta: $TIME ms"
  averageResponseTimeTitle: "Tempo medio di risposta"
  completeOutage: "Interruzione completa"
  degraded: "Degradato"
  degradedPerformance: "Prestazioni degradate"
  down: "Non funzionante"
  duration1Y: "1 anno"
  duration24H: "24 ore"
  duration30D: "30 giorni"
  duration7D: "7 giorni"
  duration: "Durata"
  durationAll: "Tutto"
  durationMin: "$DURATION minuti"
  errorHome: "Vai alla home page"
  errorIntro: "Si è verificato un errore durante il tentativo di ottenere i dettagli sullo stato più recenti."
  errorText: "Puoi riprovare tra qualche istante."
  errorTitle: "Si è verificato un errore"
  footer: "Questa pagina è [open source]($REPO), fornita da [Upptime](https://upptime.js.org)"
  history: "Cronologia"
  incidentBack: "← Torna a tutti gli incidenti"
  incidentClosedAt: "Chiuso il"
  incidentCommentSummary: "Inserito il $DATE da $AUTHOR"
  incidentCompleted: "Completato"
  incidentDetails: "Dettagli dell'incidente"
  incidentFixed: "Risolto"
  incidentOngoing: "In corso"
  incidentOpenedAt: "Aperto il"
  incidentReport: "Resoconto incidente #$NUMBER →"
  incidentScheduled: "Programmato"
  incidentTitle: "Dettagli incidente #$NUMBER"
  incidentViewOnGitHub: "Visualizza e iscriviti su GitHub"
  liveStatus: "Stato in tempo reale"
  liveStatusHtmlComment: "<!--live status-->"
  loading: "Caricamento..."
  ms: "ms"
  navGitHub: "GitHub"
  overallUptime: "Tempo di attività complessivo: $UPTIME"
  overallUptimeTitle: "Tempo di attività complessivo"
  partialOutage: "Interruzione parziale"
  pastIncidents: "Incidenti passati"
  pastIncidentsResolved: "Risolto in $MINUTES minuti con $POSTS post"
  pastScheduledMaintenance: "Manutenzioni programmate passate"
  rateLimitExceededCopyPastePAT: "Copia e incolla il tuo token"
  rateLimitExceededErrorFix: "Puoi aspettare un'altra ora e il limite del tuo indirizzo IP verrà ripristinato. In alternativa, puoi aggiungere il tuo token di accesso personale GitHub, che ti offre ulteriori 5.000 richieste all'ora."
  rateLimitExceededErrorHowCanFix: "Come posso risolverlo?"
  rateLimitExceededErrorMeaning: "Questo sito Web utilizza l'API GitHub per accedere ai dati in tempo reale sullo stato dei nostri siti Web. Per impostazione predefinita, GitHub consente a ogni indirizzo IP 60 richieste all'ora, che hai consumato."
  rateLimitExceededGeneratePAT: "Scopri come generare un token di accesso personale"
  rateLimitExceededGitHubPAT: "Token di accesso personale GitHub"
  rateLimitExceededHasSet: "Hai un token di accesso personale impostato."
  rateLimitExceededIntro: "Hai superato il numero di richieste che puoi fare in un'ora, quindi dovrai attendere prima di accedere nuovamente a questo sito web. In alternativa, puoi aggiungere un token di accesso personale GitHub per continuare a utilizzare questo sito web."
  rateLimitExceededRemoveToken: "Rimuovi token"
  rateLimitExceededSaveToken: "Salva token"
  rateLimitExceededTitle: "Limite di richieste superato"
  rateLimitExceededWhatDoesErrorMean: "Cosa significa questo errore?"
  responseTimeDay: "Tempo di risposta (24 ore)"
  responseTimeGraphAlt: "Grafico del tempo di risposta"
  responseTimeMonth: "Tempo di risposta (30 giorni)"
  responseTimeMs: "Tempo di risposta (ms)"
  responseTimeWeek: "Tempo di risposta (7 giorni)"
  responseTimeYear: "Tempo di risposta (1 anno)"
  scheduledMaintenance: "Manutenzione programmata"
  scheduledMaintenanceSummaryStarted: "Iniziato il $DATE per $DURATION minuti"
  scheduledMaintenanceSummaryStarts: "Inizierà il $DATE e durerà $DURATION minuti"
  sevelDayResponseTime: "Grafico complessivo del tempo di risposta"
  startedAt: "Iniziato il"
  startsAt: "Inizierà il"
  status: "Stato"
  up: "Funzionante"
  uptimeDay: "Tempo di attività (24 ore)"
  uptimeMonth: "Tempo di attività (30 giorni)"
  uptimeWeek: "Tempo di attività (7 giorni)"
  uptimeYear: "Tempo di attività (1 anno)"
  url: "URL"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
