# Change these first
owner: CyberLions-Italian-Community # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

user-agent: CyberLions-Italian-Community

sites:
  - name: Sito web
    url: https://cyberlions-ita.eu
    assignees:
      - Trainax
      - TheGITofTeo997
  - name: Server TeamSpeak
    check: "tcp-ping"
    url: 164.132.251.188
    port: 30033
    assignees:
      - TheGITofTeo997
  - name: SinusBot
    check: "tcp-ping"
    url: 217.182.128.229
    port: 8087
    assignees:
      - TheGITofTeo997
  - name: Infrastruttura principale
    check: "tcp-ping"
    url: 217.182.128.229
    port: 22
    assignees:
      - TheGITofTeo997

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cyberlions-ita.eu
  # baseUrl: /status
  logoUrl: https://cyberlions-ita.eu/images/brown.png
  name: CyberLions Italian Community Status Page
  introTitle: "CyberLions Italian Community Status Page"
  introMessage: "Qui puoi vedere lo stato dei nostri servizi"
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CyberLions-Italian-Community/status
      
i18n:
  url: "URL"
  status: "Stato"
  history: "Cronologia"
  responseTime: "Tempo di risposta"
  uptime: "Tempo di attivit"
  up: "游릴 Funzionante"
  degraded: "游릳 Degradato"
  down: "游린 Non funzionante"
  responseTimeGraphAlt: "Grafico del tempo di risposta"
  ms: "ms"
  responseTime: "Tempo di risposta"
  responseTimeDay: "Tempo di risposta (24 ore)"
  responseTimeWeek: "Tempo di risposta (7 giorni)"
  responseTimeMonth: "Tempo di risposta (30 giorni)"
  responseTimeYear: "Tempo di risposta (1 anno)"
  uptime: "Tempo di attivit"
  uptimeDay: "Tempo di attivit (24 ore)"
  uptimeWeek: "Tempo di attivit (7 giorni)"
  uptimeMonth: "Tempo di attivit (30 giorni)"
  uptimeYear: "Tempo di attivit (1 anno)"
  liveStatus: "Stato in tempo reale"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "游릴 Tutti i sistemi operativi"
  degradedPerformance: "游릳 Prestazioni degradate"
  completeOutage: "游린 Interruzione completa"
  partialOutage: "游릲 Interruzione parziale"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
